### ISSUE TITLE
Encapsulation in classes and immutable fields in them.

### ISSUE THREAD

**Issue by przemyslaw0** [Glasses-Neo/OOlib#123]
There is no way to make objects in classes as private, public or protected with OOlib.

Also, immutable fields in classes would be a good idea: https://stackoverflow.com/questions/26858518/idiomatic-way-to-declare-c-immutable-classes

**Comment by Glasses-Neo** [comment]
Do objects in classes mean member variables in classes? You can make member variables public by using `*`

I guess immutable fields can be implemented with getter/setter like this: https://github.com/Glasses-Neo/OOlib/issues/89

**Comment by Glasses-Neo** [comment]
I think inherited objects can refer to member variables of their parents, so Nim's unexported variables must function like protected variables by default.
```nim
type
  A = ref object of RootObj
    parentVar: int
  B = ref object of A

proc echoParentVar(self: B) =
  echo self.parentVar # will compile
```
