### ISSUE TITLE
git tagを打って欲しい

### ISSUE THREAD

**Issue by jiro4989** [Glasses-Neo/OOlib#69]
# 提案

- このリポジトリの最新の master に `git tag v0.2.2` を打ってほしい
- 以降、新バージョンが公開されるたびに `git tag vX.X.X` を打つようにしてほしい

※ 今より古いコミットについて、その当時のバージョンに合わせて `git tag` を打つまではしなくてよいと思います

# 理由

バージョン番号指定で `nimble install` ができないため

```bash
⟩ nimble install 'OOlib@0.2.1'
Downloading https://github.com/Glasses-Neo/OOlib using git
   Warning: Package 'oolib' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'oolib', but file 'tmpl.nim' is in a directory named 'oolibpkg' instead. This will be an error in the future.
      Hint: If 'oolibpkg' contains source files for building 'oolib', rename it to 'oolib'. Otherwise, prevent its installation by adding `skipDirs = @["oolibpkg"]` to the .nimble file.
       Tip: 2 messages have been suppressed, use --verbose to show them.
     Error: Downloaded package's version does not satisfy requested version range: wanted 0.2.1 got 0.2.2.
```

正常にインストールできる場合は、以下のように出力されます。

```bash
⟩ nimble install 'cligen@1.5.18'
Downloading https://github.com/c-blake/cligen.git using git
  Verifying dependencies for cligen@1.5.18
 Installing cligen@1.5.18
   Success: cligen installed successfully.
```

# 詳細

nimble でパッケージをバージョン指定してインストールする場合、バージョン情報はGitリポジトリのタグに基づいて判別されます。nimbleファイルのバージョン番号のみでは不足しています。

参考: [Versions - nim-lang/nimble](https://github.com/nim-lang/nimble#versions)

このリポジトリはタグが振られていないため、最新版のインストールしかできない状態です。

# 参考

他の nimble パッケージでバージョン番号運用をしているパッケージを紹介します

- https://github.com/itsumura-h/nim-basolato/
- https://github.com/jiro4989/faker
- https://github.com/c-blake/cligen

**Comment by Glasses-Neo** [comment]
提案ありがとうございます。修正いたします。

**Comment by Glasses-Neo** [comment]
修正しました🙇‍♂️
